<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AvaloniaVersion>12.0.5</AvaloniaVersion>
    <ReactiveUIAvaloniaVersion>12.0.3</ReactiveUIAvaloniaVersion>
    <SemiAvaloniaVersion>12.0.3</SemiAvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="ProDataGrid" Version="12.0.4" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="$(ReactiveUIAvaloniaVersion)" />
    <PackageVersion Include="Semi.Avalonia" Version="$(SemiAvaloniaVersion)" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.9" />
    <PackageVersion Include="VC-LTL" Version="5.3.1" />
    <PackageVersion Include="YY-Thunks" Version="1.2.2-beta.2" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
  </ItemGroup>
</Project>
